changelog:
  exclude:
    labels: [skip-changelog]
  categories:
    - title: Improvements
      labels: [enhancement]
    - title: Fixes
      labels: [bug]
    - title: Dependencies
      labels: [dependencies]
    - title: Other changes
      labels: ['*']
